# Server Configuration
server:
  port: 8080

# Spring Configuration
spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/autograder
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

  # Database Migration Configuration
  flyway:
    baseline-on-migrate: true

  # JPA Configuration
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true

  # Redis Cache Configuration
  cache:
    type: redis
    cache-names: runtimes
    redis:
      time-to-live: 60000
      cache-null-values: false
      use-key-prefix: true

  # Redis Connection Configuration
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

# Application-specific Configuration
app:
  security:
    jwt:
      expirationMinutes: 60
      secret: 1234
  client:
    enabled: false
    submissionResultUrl: http://localhost:8886/submission-test-result
  piston:
    url: http://piston:2000  # Use env var or default to localhost for host-based dev

# Actuator
management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
